sudo: required
services:
    - docker

before_install:
    - docker build -t gega/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true gega/docker-react npm run test
language: generic

deploy:
    provider: elastickbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "sdfsdfsfds"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
